### ISSUE TITLE
Not able to scrape pages

### ISSUE THREAD

**Issue by sirajrkhan** [s0ph1e/node-website-scraper#178]
I getting below error
========= ERROR ============
TypeError: Cannot read property 'getUrl' of null
    at Scraper.loadResource (D:\my_dir\migration\ooa\node_modules\website-scraper\lib\scraper.js:65:20)
    at receivedResponse (D:\my_dir\migration\ooa\node_modules\website-scraper\lib\scraper.js:161:10)
    at tryCatcher (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:453:14)
    at Promise._settlePromiseFromHandler (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\promise.js:687:18)
    at Async._drainQueue (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\my_dir\migration\ooa\node_modules\bluebird\js\release\async.js:17:14)

============== CODE (of course website name changed) =============
var scrape = require('website-scraper');
scrape({
  urls: ['http://www.my-web-site.com/'],
  directory: './goo',
  recursive: true,
  maxDepth: 1
}).then(console.log).catch(console.log);

**Comment by s0ph1e** [comment]
Hi @sirajrkhan 
What version of `website-scraper` do you use?
Please try `2.1.0` -  it has fix for similar problem

**Comment by sirajrkhan** [comment]
Hi .. thanks for quick response.

The version is: 3.10.10

Also, strangely it is only working for this URL: https://sitepoint.com/

I tried with/without trailing slashes and also http AND https -- no combination clicked

**Comment by s0ph1e** [comment]
version 3.10.10 of website-scraper doesn't exist
latest is 2.1.0
please check `website-scraper` version running next command in your project directory
```bash
npm list website-scraper
```

**Comment by sirajrkhan** [comment]
Hey Thanks for all the help, really appreciated. With latest npm version (2.1.0) i am able to extract access randomly few sites (like https://fbrctr.github.io/) but for few sites like (http://www.hammerite.ie/) it is returning empty JSON. The code is same though.

[ Resource {
    url: 'http://www.hammerite.ie/',
    filename: 'index.html',
    type: null,
    depth: 0,
    parent: null,
    children: [],
    saved: false } ]

**Comment by sirajrkhan** [comment]
Hey.. pls dont bother.. looks like it is due to firewall/proxy settings of the organization
